/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {

        ArrayList<String> lista = new ArrayList<>();
        ArrayList<Pessoa> agenda = new ArrayList<>();

        lista.add("POO");
        lista.add("FE");
        lista.add("RE");
        lista.add("AE");

        agenda.add(new Pessoa("Lucas", "lucas@gmail.com"));
        agenda.add(new Pessoa("Joana", "joana@gmail.com"));
        agenda.add(new Pessoa("Bernardo", "bernardo@gmail.com"));
        agenda.add(new Pessoa("Cecilia", "cecilia@gmail.com"));

        for (String elemento : lista) {
            System.out.println(elemento);
        }

        for (Pessoa colecao : agenda) {
            System.out.println(colecao);
        }

        lista.forEach(elemento-> System.out.println(elemento));

        lista.removeIf(elemento-> elemento.equals("POO"));

        lista.removeIf( Pessoa-> Pessoa.equals("Lucas"));

        agenda.forEach(System.out::println);

        lista.forEach(System.out::println);


    }
}
